### ISSUE TITLE
Rename `kw mail`

### ISSUE THREAD

**Issue by davidbtadokoro** [kworkflow/kworkflow#1027]
**Description:**

The name `kw mail` can be improved to be more descriptive. An option is `kw send-patch`.

**Note**

Please, give suggestions of names!

**Comment by AbhinavMir** [comment]
Hi! I think I can do this! I assume the changes are in `kw` shell script, where the large [switch-case](https://github.com/abhinavMir/kworkflow/blob/af4d2e3100bd33c8dd07c8dba2c42cd7af020c9b/kw#L106) is, and in the variable names and  print statements in `mail.sh` (src/mail.sh). Am I on the right track?

**Comment by rodrigosiqueira** [comment]
Yes.
You also need to update the documentation and the autocomplete files.

**Comment by JGBSouza** [comment]
I think that this issue is not being developed, in this case i would like to assign to it. I have some suggestions of names that can be used, as: kw patch-ease, kw patch-manager, kw patch-ops and kw-patchify. I think that send-patches may not work since we will have some commands as kw patch-send --send that won't work properly.

**Comment by melissawen** [comment]
TBH, I never understood why sending an e-mail (--send) is an option and not the default behaviour when no option is set. This is also the reason to think that `kw send-patch` is a good name for this feature. It means replacing `kw mail -s` by `kw send-patch`.

**Comment by lucasqml** [comment]
i'm working on this issue

**Comment by AbhinavMir** [comment]
Good to close or mark as "has candidate"?

**Comment by rodrigosiqueira** [comment]
@AbhinavMir  This is done; we are just waiting for the merge into the master branch.
