### ISSUE TITLE
Pomodoro Timer Without Tag Not Created or Displayed

### ISSUE THREAD

**Issue by gabrielsrd** [kworkflow/kworkflow#1156]
**Description:**

When attempting to use the `kw pomodoro` command to set a timer without a tag, the timer is not created and no error message is shown. However, setting a timer with a tag works as expected.

**How to Reproduce:**

1. Run the command `kw pomodoro -t 10m`
2. Check the timer status with `kw pomodoro -c`

The timer is not displayed.

3. Run the command `kw pomodoro -t 10m -g "tag"`
4. Check the timer status with `kw pomodoro -c`

The timer is displayed correctly.

**Expected behavior:**

Setting a timer without a tag should either create a timer that can be checked with `kw pomodoro -c` or display an appropriate error message if the timer cannot be created.

**Screenshots:**
![Captura de tela 2024-08-07 165155](https://github.com/user-attachments/assets/115c5535-394a-444b-a61c-2b235a357482)

**System information:**

- OS: [Ubuntu 22.04.4 LTS]
- kw Version: [ alpha
                Branch: unstable
                Commit: e84a9ca
            ]
- Bash Version: [GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)]

**Additional context:**

I will investigate whether the timer is being created but not displayed, or if the timer is not being created at all. If the timer is not being created, I will implement an error message to notify the user.

**Comment by davidbtadokoro** [comment]
Hi @gabrielsrd , and thabks for reporting this issue! The behavior of `kw pomodoro` without a tag is indeed a little strange.

I think the timer is created, but there is no record of it in our database for pomodoro sessions without tags, so that is why `kw pomodoro -c` doesn't display any info (as this commands fetches the "active" timers in the DB).

With that being said, I agree with you that we need to standardize this for at least displaying info to the user, who should see some feedback of untagged sessions. Maybe a "simple" solution would be to add a `no-tag` tag to amass these type of sessions...

**Comment by gabrielsrd** [comment]
OKay, I'll be working on this
