### ISSUE TITLE
Rename test functions

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#152]
Our test function does not have a well-defined pattern. How about standardizing it for something like this:

```
this_is_a_test_name_Test
```

What do you think @matheustavares

**Comment by matheustavares** [comment]
Well noted. This format is OK for me.

**Comment by joaoseckler** [comment]
Maybe this is too late, but shunit has a standard convention for test function names: 

`test*`

Using this convention reduces boilerplate code because it spares the need for the `suite` function. From their [documentation](https://github.com/kward/shunit2/):

> When shUnit2 is sourced, it will walk through any functions defined whose name starts with the string test, and add those to an internal list of tests to execute. Once a list of test functions to be run has been determined, shunit2 will go to work.

A rough estimate for the current unstable branch shows that about 150 lines would be saved:

```
$ sed -nE -e '/^function suite/,/}$/p' *.sh | wc -l
153
```

Do you think it's worth making this change?
