### ISSUE TITLE
Make kw instalation closer to unix standards

### ISSUE THREAD

**Issue by matheustavares** [kworkflow/kworkflow#50]
kw is currently being installed at ~/.config/kw, which dosen't seem so good (since it's a dir for configurations, not code). Shouldn't we install kw somewhere else, such as ~/.kw, for example?

Also, we could add kw to PATH (or create an alias) instead of loading it to bash. This change would also make the subshells in kw.sh unnecessarily and the variables "src_script_path" and "external_script_path" not visible externally, which is good.

(proposed by @capellaresumo and I)

**Comment by rodrigosiqueira** [comment]
1. After the first installation, we could create an alias in the current terminal
2. Probably the driver is the solution for all of our problems :-)

**Comment by rodrigosiqueira** [comment]
@matheustavares could you detail your view? I remembered that you suggested following the git way.

**Comment by matheustavares** [comment]
Hi, @rodrigosiqueira 

Sure! My idea, based on how Git does, was to install all the source files that should not be directly executed (the `src/*` files) at `~/<username>/lib/kw` (or `~/<username>/libexec/kw` \[1]) and the only source that is to be executed, `kw`, at `~/<username>/bin`. For a system-wide installation, these two would be respectively replaced by `/usr/lib/kw/` and `/usr/bin`. The nice thing is that a simple `--prefix=` option at `setup.sh` would be sufficient for the user to specify where to install (and `sudo` in case of system-wide, of course). 

We still would have to check where to store configuration files and user data (such as the one generated by `kw configm` and the sounds for completion alert). I was thinking of using `~/<username>/.kw/` for that, but there may be a unix place for that as well.

So, what do you think of this approach?

\[1]: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html

**Comment by rodrigorsdc** [comment]
Hi there!

I have been implementing kw into a Debian package. To facilitate my packaging works, I created a 
Makefile to make kw installation to respect unix stardard. That Makefile put executable kw at /usr/share/kw, src directory at /usr/share/kw/src, sound directory at /usr/share/kw/sounds and deploy_rules at /usr/share/kw/deploy_rules. Also, the Makefile build the manpage using rst2man command and put that at /usr/share/man/man1. The bash_autocomplete.sh file is put at /usr/share/bash-completion/completions.

Because these changes, I had to modify kw file to accept the new path (new src/ and deploy_rules/ paths).

About config files, I adopted the following strategy: if home's user doesn't contains .config/kw directory, kw script will create .config/kw dir and put kworkflow.config at the new directory.

If you have interest, I can open a pull request committing these changes.

**Comment by rodrigosiqueira** [comment]
@rodrigorsdc 
First of all, thank you very much for your effort to package kw to Debian; this will be a vast improvement for us. I would like to suggest you send these changes as a PR and we can improve this together. What do you think?

Ps.: Are you using kw test on your package? Take a look on this https://people.debian.org/~mpitt/autopkgtest/README.package-tests.html

**Comment by rodrigosiqueira** [comment]
Done!
