### ISSUE TITLE
Add support to Fedora-based systems

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#567]
**Description:**

Currently, kw deploy only works for Debian and ArchLinux families. Let's expand kw distro support and add a Fedora-based system as a target.

**Why:**

Many kernel developers use Fedora as their base system.

**Target user:**

* Kernel developers that use Fedora.
* Developer that needs to support stable distros such as RedHat.

**How to implement it:**

First step:
* Learn how to install a custom kernel in a Fedora distro manually.
* Learn about:
   * Pre-setup (required packages, config file, etc)
   * How to generate the initramfs
   * Default bootloader and how to update it

In a few words, this work can be divided into the following commits:
* Commit 1: Add setup step for fedora system. Here we want to install the required package, and we might need to configure something else. You will need to create the `fedora.sh` file at `src/plugins/kernel_install/`
* Commit 2: Introduce Fedora deploy. In theory, at this stage, you just need to enable the initramfs update for the fedora system and other minor details. You will probably spend most of your time implementing tests and validating the correct behavior.

**Comment by mairacanal** [comment]
Currently, I'm working on this feature and I stepped into a small problem that I would like to pitch to the kw community. Fedora uses grub2 commands (like grub2-mkconfig) to manage the grub. The grub update on kw is declared through a variable DEFAULT_GRUB_CMD_UPDATE, which uses the command grub-mkconfig, instead of grub2-mkconfig.

 I was thinking about a sophisticated solution to this problem and I thought about creating a DEFAULT_GRUB_CMD_UPDATE for each distribution, but on the other side, this could scale pretty fast as the number of distros supported by kw grows.
 
 Have you guys any thoughts on this issue?

**Comment by rodrigosiqueira** [comment]
In OO we have a design pattern named "factory" and "simple factory", the idea is quite simple:
1. Provide a generic API
2. Provide a mechanism to choose a specific strategy in run time
3. Use the specific strategy

I think we could try to implement something like this inside kw.

**Comment by mairacanal** [comment]
Do you believe this could suit well inside the grub.sh file?
