### ISSUE TITLE
.config file is not deleted with `kw -r [name]` command

### ISSUE THREAD

**Issue by mairacanal** [kworkflow/kworkflow#595]
**Description:**

The .config file is not deleted with the use of the command `kw -r [name]`. This can be checked by the fact that `kw g -l` still shows the config file and also the file is still on the folder `~/.local/share/kw/configs/configs`.

**How to Reproduce:**

```
➜ kw g -l
Name                           | Description

AMDGPU                         |
NO_DCN_CONFIG                  |

➜ kw g -r AMDGPU
This operation will remove AMDGPU from kw management
Are you sure that you want to proceed? [y/N]: y
The AMDGPU config file was removed from kw management

➜ kw g -l
Name                           | Description

AMDGPU                         |
NO_DCN_CONFIG                  |
```

**Expected behavior:**

I would expect to see the AMDGPU .config file deleted in this specific case.

**Screenshots:**

![image](https://user-images.githubusercontent.com/61601791/164943889-16a9d375-ca03-433a-832b-7887167f8eff.png)

**System information:**

 - OS: Fedora 35
 - Kw Version: alpha / Branch: unstable / Commit: 9302673
 - Bash Version: zsh 5.8.1

**Comment by pomba123** [comment]
Can't reproduce this error on  commit [414fe8f](https://github.com/kworkflow/kworkflow/commit/414fe8fbad7118226b6053f632641380e3f0d581).

config,g - Set kw config options - The g option now is used to manage the config files of kw

kernel-config-manager,k - The k option now is used to manage config files of the target kernel

The commands have the expected behavior.

**Comment by mairacanal** [comment]
I just reproduced on 52907dccb9956a2e17bc4539af70769b461ca9f4 on Fedora 36.
![image](https://user-images.githubusercontent.com/61601791/191862561-a1cbecfc-c501-4353-bb42-32bfcebee5a3.png)

**Comment by mairacanal** [comment]
I did:
```
cd ~/.local/share/kw/configs
git config --local user.email <my email>
```

The output was: `fatal: --local can only be used inside a git repository`

**Comment by Kamorst** [comment]
Is there any tracked .config file? If not, first create the git repo with `kw k  -s TMP` inside a linux git repo.
The only way I could replicate this bug is by creating the git which tracks the config files before setting user.email and user.name globally but the above [commands](https://github.com/kworkflow/kworkflow/issues/595#issuecomment-1263995398) fixed the issue.

**Comment by mairacanal** [comment]
> Is there any tracked .config file? If not, first create the git repo with `kw k -s TMP` inside a linux git repo. The only way I could replicate this bug is by creating the git which tracks the config files before setting user.email and user.name globally but the above [commands](https://github.com/kworkflow/kworkflow/issues/595#issuecomment-1263995398) fixed the issue.

There are 4 config files tracked by the .config file.

**Comment by rodrigosiqueira** [comment]
@mairacanal we reworked how we manage the .config file in the latest version, could you confirm if this is still an issue?

**Comment by mairacanal** [comment]
Not anymore! Thanks for working on it!

**Comment by rodrigosiqueira** [comment]
Thanks for checking!
