### ISSUE TITLE
Add an option not to use kw env if a user is in an env

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#746]
**Description:**

kw env feature is used for isolating different kernel builds inside envs; however, kw also supports in-tree kernel build. We need a mechanism to allow users to "exit" the env feature. We can have something like this:

```
$kw env --no-env
```

This command should:
1. Copy the current `env` files to `.kw/` folder. Remember that envs are a simple symbolic link to another path; if we don't have any env, we just need to drop those symbolic links in favor of the actual file.
2. Notify users about the consequence and ask them if they really want to proceed.

**Comment by aquilamacedo** [comment]
i'm working on it.

**Comment by aquilamacedo** [comment]
Hi @rodrigosiqueira. I have a doubt about this issue.

![image](https://user-images.githubusercontent.com/43859386/206881750-354e1742-7858-49aa-8457-0e0ae073761f.png)

There is a code snippet in the use_target_env function that moves the default .config files to a temporary path using `mktemp` (line 72 of the code).

I didn't understand the reason to send the .config files from the default environment to a temporary path. I believe that a temporary path is not the best option to store these files, since `/tmp/` writes in volatile memory.

So I thought of creating a directory inside the .kw, something like (_.kw/default/_) to move these .config files from the default environment to this directory instead of a temporary path, it would be easier to retrieve these files to use in `- -no-env` parameter.

What do you think about this?

**Comment by rodrigosiqueira** [comment]
Hi @aquilamacedo ,

If we are not using any env, the `.kw` folder will look like this:
```
build.config  deploy.config  kworkflow.config  mail.config  notification.config  remote.config
```
However, when we create an env, we will replace all of those 'real' config files with a symbolic link pointing to `./kw/ENV_NAME/`. Notice from the comments in lines 68-69 that we don't want those 'real' files there if the user is using envs; for this reason, I moved them to a tmp folder. It was intentional to move to a temporary folder since this is now garbage.

For this specific issue, you can check:
1. If the user is using some specific env and doesn't want to use it anymore, just eliminate all the symbolic links and copy the current env config files into `.kw/` folder. You may also want to ask the user if they want to use the current env as the default for the case without env.
2. If the user is not using any env, you don't need to do anything.

**Comment by rodrigosiqueira** [comment]
@aquilamacedo any update here? I want to complete the two env issues open to update the master branch.
