### ISSUE TITLE
Automatic system setup doesn't work after a full update on SteamOS 

### ISSUE THREAD

**Issue by melissawen** [kworkflow/kworkflow#754]
**Description:**

After a full update of the SteamOS the /boot partition is totally clean and also package previously installed in the system, that means we lost the deployment setup. As KW saves the env status in /opt/kw/status, kw deploy doesn't set the environment again, and we can't deploy because we miss some dependencies there. To overcome this issue, we need to manually remove the /opt/kw/status and try to deploy again.

```
* Sending kernel package (5.18.0-amd-staging-drm-next+.kw.tar) to the remote
     18,430,995 100%   15.15MB/s    0:00:01 (xfr#1, to-chk=0/1)
tar (child): lzop: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Warning (2): Could not extract module archive.
Error is not recoverable: exiting now
Unable to correctly uncompress kw package in the target system
-> Execution time: 00:00:03
```

**How to Reproduce:**

This issue is only reproducible after a full system update. With that, just try `kw bd` to see the issue.

**Expected behavior:**

Maybe we should delete the /opt/kw/status all the time or add an option (flag?) if we want to do it during `kw deploy`
**Screenshots:**

**System information:**

 - OS: SteamOS
 - kw Version: unstable
 - Bash Version: version 5.2.2(1)-release

**Comment by siddhanthrathod** [comment]
Can I take this ? @rodrigosiqueira

**Comment by siddhanthrathod** [comment]
@melissawen  are you using steamOS based on debian or arch ? The older debian one has been discontinued now I guess as they have removed it form the website as well

**Comment by rodrigosiqueira** [comment]
Technically, you don't need SteamOS for that. Let me try to summarize the root cause:

1. When deploy a new kernel, kw has a setup step that configures some basic things and installs some packages.
2. We only want to run (1) the first time. To keep track of that, we create a status file at /opt/kw/status.
3. If the status file exists, kw deploy will skip the setup part.

The problem here came from the fact that SteamOS uses an A/B partition. In very few words, portion A will have the current kernel, but when a new version of the OS is released, A becomes B, and the new version becomes A (this is a huge simplification, please read more about it).

Based on how kw works and SteamOS works, this is how this bug happens:

1. The user deploy a new kernel to SteamOS
2. A few weeks later, Valve released a new version
3. Users updated it, and now, all the packages previously installed are removed. However, /opt/kw/status still there
4. Users try to deploy a new kernel, but it fails because kw will see that the status file exists, and it will skip the setup phase, but after the new partition update, those packages are no longer available.

One idea to fix this issue could be to create a symbolic link to the status file under the /boot directory and make kw check it instead of check /opt/kw/status directly. If the A/B partition updates, the symbolic link will be removed, and that way kw will know that it needs to install all missing packages again. This is just one idea that I had while I typed this message; feel free to propose anything else.

**Comment by siddhanthrathod** [comment]
Thanks for the reply @rodrigosiqueira  Yes SteamOs3 also uses the A/B system so I should work on it also thanks for explaining it'll make things way easier and I'll read more about the A/B sys and work on it.
